#99: replace createOrThrow with createOrAssert
timemates/backend pull request #125
Opened 2023-05-30 18:03 UTC by y9slavabogu

2023-05-30 19:56 UTC, y9vad9 requested changes
You forget about `:domain` layer

2023-05-31 16:56 UTC, y9slavabogu commented
Okay. I will do it today.

2023-05-31 21:37 UTC, y9vad9 requested changes

2023-05-31 21:37 UTC, y9vad9 commented on data/build.gradle.kts
> +    implementation(projects.features.testUtils)
testImplementation here

2023-06-01 21:29 UTC, y9vad9 requested changes

2023-06-02 10:18 UTC, y9vad9 approved these changes

2023-06-02 14:45 UTC, merged